### ISSUE TITLE
How to export the onnx of the centermask?

### ISSUE THREAD

**Issue by Damilytutu** [youngwanLEE/centermask2#10]
Hi, because you built the centermask based on detectron2, I'm a little confused about how to export the onnx of the model. Hope you can give some help, thank you so much!

**Comment by youngwanLEE** [comment]
@Damilytutu 

I'm not familiar with the onnx and don't have a plan to export the onnx of the model yet.

Sorry.

**Comment by yutao007** [comment]
好吧，那楼主的算法只是实验室的算法了，在项目实践中的很耗硬件。
