### ISSUE TITLE
Where does the improvements come from?

### ISSUE THREAD

**Issue by huangh12** [youngwanLEE/centermask2#17]
From the table given in readme, the AP increase by 1.2 point from implementation of **maskrcnn-benchmark** to **Detectron2**.

![图片](https://user-images.githubusercontent.com/18748036/76513257-fb281e00-6490-11ea-9403-4a095ab8f427.png)

Could you please uncover where the improvements comes from？

Thank you.

**Comment by youngwanLEE** [comment]
@huangh12 

Mm.. I also don't know the exact reason. 

I just implemented CenterMask concept on top of detectron2.

detectron2 is improved from [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark). 

Would you like to ask detectron2 team?
