### ISSUE TITLE
How to eval in Test-time Augmentation way？

### ISSUE THREAD

**Issue by Linwei-Chen** [youngwanLEE/centermask2#33]
How to eval in Test-time Augmentation way？

**Comment by youngwanLEE** [comment]
With 

`TEST.AUG.ENABLED True`

for example,

python train_net.py

`python train_net.py --config-file "configs/centermask/centermask_V_39_eSE_FPN_ms_3x.yaml" --num-gpus 1 --eval-only MODEL.WEIGHTS centermask2-V-39-eSE-FPN-ms-3x.pth TEST.AUG.ENABLED True`
