### ISSUE TITLE
ImportError CityscapesEvaluator (with recent Detectron2 git version)

### ISSUE THREAD

**Issue by velaia** [youngwanLEE/centermask2#34]
Hello, thank you for your very interesting work with CenterMask2!

While giving CenterMask2 a test shot with the latest Detectron2 version (from GitHub) the `train_net.py` ended with an Import Error:
```
> python train_net.py --config-file "configs/centermask/centermask_lite_V_19_eSE_FPN_ms_4x.yaml"
Traceback (most recent call last):
  File "train_net.py", line 13, in <module>
    from detectron2.evaluation import (
ImportError: cannot import name 'CityscapesEvaluator' from 'detectron2.evaluation' (/home/daniel/git/detectron2/detectron2/evaluation/__init__.py)
```

I did a little digging and found out that there has been a [change a couple of days ago in Detectron2](https://github.com/facebookresearch/detectron2/commit/e7aa570c268c25d5b05b0647dcdb4041eddfd054#diff-0142beb7d262606a7ec9de193a14e541). As far as I understand the class `CityscapesEvaluator` still exists but is not contained in the `__init__.py` anymore. The functionality of the class seems to have partly moved into `CityscapesInstanceEvaluator` and an additional class `CityscapesSemSegEvaluator` has been introduced.

I'm not sure whether the Detectron2 version has changed but I find that if I compile my version (from GitHub) it does say:
```
>>> print(detectron2.__version__)
0.1.2
```
I'm not sure how to best handle this - possibly by adjusting the code and adding a requirements(.txt) file when fixing the issue. I myself (locally) will replace the import of `CityscapesEvaluator` with `CityscapesInstanceEvaluator`. Will try to create a GitHub pull request but as I'm not familiar with this system please correct me if I'm doing something wrong.

Thank you and greetings from Hongdae, Seoul.

**Comment by dimabendera** [comment]
You must change CityscapesEvaluator to CityscapesInstanceEvaluator

```python3
from detectron2.evaluation import (
    CityscapesInstanceEvaluator,
    COCOPanopticEvaluator,
    DatasetEvaluators,
    LVISEvaluator,
    PascalVOCDetectionEvaluator,
    SemSegEvaluator,
    verify_results,
)
```

**Comment by velaia** [comment]
> You must change CityscapesEvaluator to CityscapesInstanceEvaluator

Agreed. It's also important to make sure that the requirements.txt is adjusted accordingly. Otherwise CenterMask might not work with previous versions of Detectron2 anymore.
