### ISSUE TITLE
The problem of mask_iou occupying excessive memory

### ISSUE THREAD

**Issue by ZepingZhou** [youngwanLEE/centermask2#37]
Now, I am training centermask2 with resnest50 backbone on a single 1080 GPU. I find that if i set MASK_IOU = False, IMS_PER_BATCH can up to 4. However, IMS_PER_BATCH will be limited to 2 with MASK_IOU == True. Is this phenomenon normal? Does anyone know what caused this?

**Comment by youngwanLEE** [comment]
If you turn on the MASK_IOU, you use maskiou branch which needs memory footprint.

It is normal. 

You can find the details of the maskiou branch in our paper.
