### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.VOVNET'

### ISSUE THREAD

**Issue by alatriste-lee** [youngwanLEE/centermask2#41]
[https://github.com/youngwanLEE/centermask2#installation](url)

> All you need to use centermask2 is detectron2. It's easy!
> you just install detectron2 following INSTALL.md.
> Prepare for coco dataset following this instruction.

No, it's not easy. It can't work.

Here is what I did:

1.followed install instruction and then detectron2-0.1.3+cu101-cp37-cp37m-linux_x86_64.whl can work.
2.download centermask2-V-99-eSE-FPN-ms-3x.pth and this repo, set  as

>cfg.merge_from_file("/home/pc/centermask2/configs/centermask/centermask_V_99_eSE_FPN_ms_3x.yaml")

> cfg.MODEL.WEIGHTS = "/home/pc/dataset/centermask2-V-99-eSE-FPN-ms-3x.pth"

3. train
4. get the message KeyError: 'Non-existent config key: MODEL.VOVNET'.

so, are there any paths needed to set in environment? 

Thx a lot

**Comment by YacobBY** [comment]
_Edit: Author fixed some broken stuff._ 
 I got some of it working though (disclaimer, have only been messing around with it for a little while)

You can get the imports working by cloning the repo, making a setup.py file in the repo and running pip install -e RepoNameHere (probably centermask2)

setup.py example:

```
#!/usr/bin/env python

from distutils.core import setup

setup(name='centermask',
      version='1.0',
      description='centermask test',
      author='tmp',
      author_email='n@n.com',
      url='placeholder',
      packages=[''],
     )
```

then fix imports https://github.com/youngwanLEE/centermask2/issues/34#issuecomment-630888650

edit: ioumask issue has been fixed

and finally you can use this code to test it https://github.com/youngwanLEE/centermask2/issues/36

**Comment by jgsch** [comment]
I assume you're using `get_cfg` of detectron2 directly. But if you look at `train_net.py`, it has its own imported `get_cfg` function, cf [line 26](https://github.com/youngwanLEE/centermask2/blob/master/train_net.py#L26). That's the one you have to import.

```
from detectron2.engine import default_setup
from centermask.config import get_cfg  # add centermask folder to your PATH if needed

cfg = get_cfg()
cfg.merge_from_file(args.config_file)
cfg.merge_from_list(args.opts)
cfg.freeze()
default_setup(cfg, args)
```

**Comment by youngwanLEE** [comment]
@alatriste-lee 

Did you use the our [train_net.py](https://github.com/youngwanLEE/centermask2/blob/master/train_net.py) not detectron2/tools/train_net.py?

Please read this [guideline ](https://github.com/youngwanLEE/centermask2#training).

**Comment by alatriste-lee** [comment]
> Centermask2 is straight up lying. It's not runnable out of the box and a lot is just broken and outdated. It seems like the authors have already abandoned it. I got some of it working though (disclaimer, have only been messing around with it for a little while)
> 
> You can get the imports working by cloning the repo, making a setup.py file in the repo and running pip install -e RepoNameHere (probably centermask2)
> 
> setup.py example:
> 
> ```
> #!/usr/bin/env python
> 
> from distutils.core import setup
> 
> setup(name='centermask',
>       version='1.0',
>       description='centermask test',
>       author='tmp',
>       author_email='n@n.com',
>       url='placeholder',
>       packages=[''],
>      )
> ```
> 
> then fix imports [#34 (comment)](https://github.com/youngwanLEE/centermask2/issues/34#issuecomment-630888650)
> 
> Then you probably need to fix the broken ioumasks [#32 (comment)](https://github.com/youngwanLEE/centermask2/issues/32#issuecomment-627043376)
> 
> and finally you can use this code to test it #36

Thank you, I'll try

**Comment by alatriste-lee** [comment]
> I assume you're using `get_cfg` of detectron2 directly. But if you look at `train_net.py`, it has its own imported `get_cfg` function, cf [line 26](https://github.com/youngwanLEE/centermask2/blob/master/train_net.py#L26). That's the one you have to import.
> 
> ```
> from detectron2.engine import default_setup
> from centermask.config import get_cfg  # add centermask folder to your PATH if needed
> 
> cfg = get_cfg()
> cfg.merge_from_file(args.config_file)
> cfg.merge_from_list(args.opts)
> cfg.freeze()
> default_setup(cfg, args)
> ```

Thank you, this could help a lot.

**Comment by alatriste-lee** [comment]
> @alatriste-lee
> 
> Did you use the our [train_net.py](https://github.com/youngwanLEE/centermask2/blob/master/train_net.py) not detectron2/tools/train_net.py?
> 
> Please read this [guideline ](https://github.com/youngwanLEE/centermask2#training).

No, GPU in use now,  I'll give it a try another day this week. Thank you for reply.

**Comment by alatriste-lee** [comment]
> RuntimeError: CUDA out of memory. Tried to allocate 2.49 GiB (GPU 0; 7.93 GiB total capacity; 4.51 GiB already allocated; 1.52 GiB free; 5.36 GiB reserved in total by PyTorch)

Sorry, lack of money limits imagination.
