### ISSUE TITLE
how to  eval  using  json file downloaded in  model merics 

### ISSUE THREAD

**Issue by GittersYang** [youngwanLEE/centermask2#43]
i want to evaluate model using json file ,not using .pth file. 

how to modify evaluation code ?

**Comment by Tongtong-allure** [comment]
Hi, can you tell me how you visualize the results?

**Comment by GittersYang** [comment]
> Hi, can you tell me how you visualize the results?

you can try to  find some tips in detectron2.  https://github.com/facebookresearch/detectron2
