### ISSUE TITLE
Question about training own datasets

### ISSUE THREAD

**Issue by LiXm1002** [youngwanLEE/centermask2#47]
Thanks for sharing!
I met a problem when training with my own dataset. In the begining, the loss seems very small, then they become zero.
And there was no output during the test.
<img width="1303" alt="截屏2020-06-29 下午10 04 58" src="https://user-images.githubusercontent.com/39939478/86015940-c7c7ca00-ba54-11ea-86dd-1fb258a73e54.png">

Can someone tell me where the problem is?

**Comment by heizie** [comment]
Hi, did you solve this?
I've met also same problem, when i train only for 1 class. If i train for 2 classes, and didn't change the NUM_CLASSES, the results are seems very bad. If I change the NUM_CLASSES, the loss are going to vanish in about 1000 iter
