### ISSUE TITLE
About the inference time

### ISSUE THREAD

**Issue by Liu199604** [youngwanLEE/centermask2#49]
I do the evaluation with the model centermask2-lite-V-39-eSE-FPN-ms-4x.pth on 1080Ti, the result shows that the inference pure computation time is about 50ms per image,  it is much slower than the result on paper. So is there something wrong or I add more computation time? Could you help me? Thank you.

**Comment by Quentinmht** [comment]
Note
We measure the inference time of all models with batch size 1 on the same V100 GPU machine.

And for lite
Note that The inference time is measured on Titan Xp GPU for fair comparison with YOLACT.

**Comment by youngwanLEE** [comment]
Please re-open if you need more information.
