### ISSUE TITLE
python environment

### ISSUE THREAD

**Issue by xmba15** [youngwanLEE/centermask2#50]
Hi @youngwanLEE 
Thanks for the nice work.
The current dependency for pytorch that is mentioned in README is 1.3.1.
However, the dependency for detectron2 is pytorch >= 1.4 as mentioned in [HERE](https://github.com/facebookresearch/detectron2/blob/master/setup.py#L15)
Can you clarify this? Maybe it might be better to hardcode the dependencies into a requirements.txt or setup.py

**Comment by youngwanLEE** [comment]
@xmba15 

I update the code.

Please re-open this issue if you find any problem.
