### ISSUE TITLE
Installing Detctron2 does NOT install centermask :(

### ISSUE THREAD

**Issue by ghost** [youngwanLEE/centermask2#51]
have tried 

	pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.5/index.html

and

	python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

and 

	git clone https://github.com/facebookresearch/detectron2.git
	python -m pip install -e detectron2

None install centermask

Is there a wheel somewhere for this module?

**Comment by ShreyNiraula** [comment]
Did you solve? I just started using it and I am also stuck... Do I clone the repo itself?

**Comment by youngwanLEE** [comment]
@whillas 

centermask does not need installation by itself.

Your problem is related to detectron2.

Why don't you ask or find the information from detectron2?

Please re-open this issue if you find the problem related to this centermask2.
