### ISSUE TITLE
Centermask uses ROIPooling, so it should be two-stage instance segmentation.

### ISSUE THREAD

**Issue by shoutOutYangJie** [youngwanLEE/centermask2#52]
Why do you say it is one-stage?

**Comment by stigma0617** [comment]
@shoutOutYangJie

In the perspective of object detection, 

Using Region Proposal Network (RPN) or not determines a two-stage or one-stage method.

Compared to Mask R-CNN based Faster -RCNN, CenterMask uses a one-stage anchor-free object detector, FCOS.

**Comment by shoutOutYangJie** [comment]
> @shoutOutYangJie
> 
> In the perspective of object detection,
> 
> Using Region Proposal Network (RPN) or not determines a two-stage or one-stage method.
> 
> Compared to Mask R-CNN based Faster -RCNN, CenterMask uses a one-stage anchor-free object detector, FCOS.

You use FCOS, but also ROIPooling. At second stage, you use poolling feature to obtain mask. right? it is second-stage mask.
