### ISSUE TITLE
Warning & Slow problem 

### ISSUE THREAD

**Issue by hyunaseo** [youngwanLEE/centermask2#53]
First, thanks for releasing your code. 

I'm trying to run the model with demo.py and using three Titian GPU for running your code.
But it takes quite longer than I expected for video prediction, and after quite long time I got the result but there is no bounding box in my video. 

I used centermask_lite_V_39_eSE_FPN_ms_4x.yaml weights and when I start the code, there is a warning
" WARNING [07/29 19:58:36 d2.config.compat]: Config '../configs/centermask/centermask_lite_V_39_eSE_FPN_ms_4x.yaml' has no VERSION. Assuming it to be compatible with latest v2. "

**Comment by youngwanLEE** [comment]
@hyunas1996 
The demo script is not optimized for speed, which is the same problem with detectron2.
Feel free to enhance the inference program and send a pull request.
Thanks
