### ISSUE TITLE
Training with transfer Learning

### ISSUE THREAD

**Issue by RMalikM** [youngwanLEE/centermask2#60]
@youngwanLEE 
I am training `centermask2-V-99-eSE-FPN-ms-3x` using transfer learning. If I am not wrong, it can be done by setting `MODEL.BACKBONE.FREEZE_AT` parameter in config file. In detectron2, by [default](https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py#L133) this is set to 2. Which works for resnet and other models available in detectron2. For centermask2, in `Base-CenterMask-VoVNet.yaml` it is set to 0. As per my understanding it will start the training from scratch.
My question is, how do we choose this value for vovnet?

**Comment by youngwanLEE** [comment]
In my experience, when tranfer learning, `MODEL.BACKBONE.FREEZE_AT=0` better than `2`.

**Comment by youngwanLEE** [comment]
Please re-open this issue if you need more information.
