### ISSUE TITLE
Multi GPU for demo.py

### ISSUE THREAD

**Issue by hyunaseo** [youngwanLEE/centermask2#66]
I have one more question!

I'd like to run the demo.py with multi gpus!
Well, I know that centermask lite version is faster than YOLACT,
but for higher accuracy, I want to use centermask2 normal version with DCN :-)

So for this way, multi gpu running is available?

**Comment by youngwanLEE** [comment]
I just followed detectron2's demo script.

It may be possible to use multi-gpus setting.

**Comment by youngwanLEE** [comment]
Please re-open this issue if you encounter this problem.
