### ISSUE TITLE
How to train centermask2 on my dataset

### ISSUE THREAD

**Issue by yangfei963158659** [youngwanLEE/centermask2#67]
hi,I want to train centermask2 on my dataset,what do i do?

**Comment by Paragjain10** [comment]
> hi,I want to train centermask2 on my dataset,what do i do?

Hey @yangfei963158659 i am trying to do the same, i want to train centremask2 for my own datasets. Could you tell me what are steps.

**Comment by youngwanLEE** [comment]
@yangfei963158659 @Paragjain10 

There are the same issues related to training on the custom dataset.

Also, since this project is based on detectron2, you can more information from detectron2.
