### ISSUE TITLE
No such file or directory: 'datasets/coco/annotations/instances_train2017.json'

### ISSUE THREAD

**Issue by CodingMice** [youngwanLEE/centermask2#7]
When I run "python train_net.py --config-file "configs/centermask/centermask_lite_V_39_eSE_FPN_ms_4x.yaml" --num-gpus 8 ", it can not find the coco json file.

**Comment by jgsch** [comment]
Did you format your dataset [like recommended](https://github.com/facebookresearch/detectron2/blob/master/datasets/README.md) by detectron2

**Comment by youngwanLEE** [comment]
@CodingMice 

Firstly, you have to prepare coco dataset following this [instruction](https://github.com/facebookresearch/maskrcnn-benchmark#perform-training-on-coco-dataset) and or this [guide](https://github.com/facebookresearch/detectron2/tree/master/datasets).

**Comment by unrue** [comment]
I have the same problem. Reading the manual and using the script "prepare_for_tests.sh", are generated:
val2017 and annotation directories with instances_val2017_100.json file. No train files are generated and the json file have "100" in the name, that is unexpected. Maybe some updated of the script is necessary? Thanks.
