### ISSUE TITLE
Error when starts training Center Mask

### ISSUE THREAD

**Issue by haderalim** [youngwanLEE/centermask2#72]
![Screen Shot 2020-11-16 at 12 00 11 PM](https://user-images.githubusercontent.com/13840464/99239297-8bc6b300-2803-11eb-971c-98f06730846f.png)

In train_net.py:-

- The init function in "DefaultTrainer" takes 1 positional argument, but in train_net.py... 4 were given.

- If I change super(DefaultTrainer, self).__init__(model, data_loader, optimizer) to super(DefaultTrainer, self).__init__(cfg) it is gives another error. So how can I fix this problem?

**Comment by haderalim** [comment]
@youngwanLEE

**Comment by Peter-weng** [comment]
just delete super(DefaultTrainer, self).init(model, data_loader, optimizer) 
and use it super().__init__(cfg) that maybe ok

**Comment by youngwanLEE** [comment]
@haderalim @Peter-weng update the code. 
Please re-open this issue if the problem continues.
