### ISSUE TITLE
CenterMask2 with pytorch > 1.6 doesn't work

### ISSUE THREAD

**Issue by ApelSYN** [youngwanLEE/centermask2#77]
In autumn, new GPUs from NVIDIA 30xx series were released, which only work on CUDA> = 11.xx. In order for GPU 30xx to work, you need to install pytorch> = 1.7. Detectron2 will work fine with pytorch 1.7, CenterMask will not work with new pytorch.

Are you planning to support new torch versions?

**Comment by youngwanLEE** [comment]
@ApelSYN 
Thanks for your attention.

I have a plan to update this repo for compatibility with the latest detectron2 & CUDA versions in the near future.

**Comment by youngwanLEE** [comment]
@ApelSYN 

Could you detail your problem or log?

**Comment by youngwanLEE** [comment]
@ApelSYN 
I update the code for compatibility with pytorch1.7 and the latest detectron2.

Please re-open this issue if you encounter this problem again.

**Comment by ApelSYN** [comment]
Now all working fine. Thanks.
