### ISSUE TITLE
NUM_CLASSES on custom dataset ?

### ISSUE THREAD

**Issue by jgsch** [youngwanLEE/centermask2#8]
I'm trying to change the number of classes the network can detect. By using the exact same pipeline with another network I can get results but with CenterMask I get nothing at all. Looks like the network stays on the 80 COCO classes.

I've changed all the cfg keys containing `NUM_CLASSES` :
```
cfg.MODEL.ROI_HEADS.NUM_CLASSES = num_classes
cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = num_classes
cfg.MODEL.RETINANET.NUM_CLASSES = num_classes
cfg.MODEL.FCOS.NUM_CLASSES = num_classes
```
I guess I'm missing something?

**Comment by youngwanLEE** [comment]
I think you set them up properly. 

Are there other problems? 

When I use this project for face detection, it works well.

**Comment by jgsch** [comment]
It was actually working, it was a hyperparameter problem. Thank you for your answer!

**Comment by Kenneth-X** [comment]
> I'm trying to change the number of classes the network can detect. By using the exact same pipeline with another network I can get results but with CenterMask I get nothing at all. Looks like the network stays on the 80 COCO classes.
> 
> I've changed all the cfg keys containing `NUM_CLASSES` :
> 
> ```
> cfg.MODEL.ROI_HEADS.NUM_CLASSES = num_classes
> cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = num_classes
> cfg.MODEL.RETINANET.NUM_CLASSES = num_classes
> cfg.MODEL.FCOS.NUM_CLASSES = num_classes
> ```
> 
> I guess I'm missing something?

where is the cfg.MODEL.ROI_HEADS.NUM_CLASSES?? i can not find it can you help me ?

**Comment by huoyiyang** [comment]
> It was actually working, it was a hyperparameter problem. Thank you for your answer!

hi ，how did you solve it, i met the similar problem
