### ISSUE TITLE
Not getting good results with pretrained weights on CPU

### ISSUE THREAD

**Issue by cansik** [youngwanLEE/centermask2#80]
I tried to use the centermask2 on a CPU in WSL and after some forth and back it seems to run. But the results I get are really bad, I can not get it to recognize anything on the images (for example [COCO_val2014_000000012639.jpg](https://raw.githubusercontent.com/youngwanLEE/CenterMask/master/demo/images/COCO_val2014_000000012639.jpg)). Here is the command I use to inference it on an image (maybe interesting as well for others who struggled running this on a CPU):

```
python demo/demo.py --config-file "configs/centermask/centermask_V_39_eSE_FPN_ms_3x.yaml" --input COCO_val2014_000000012639.jpg --output output --confidence-threshold 0.1 --opts MODEL.DEVICE cpu
```

With a confidence-threshold set to `0.05` it starts to recognize something (but it's mostly uselsess). Do I miss something regarding the model or the input data?

Would be great if you could give me a hint on how to use  the pre-trained model.

**Comment by youngwanLEE** [comment]
You should add this argument `MODEL.WEIGHTS centermask2-V-39-eSE-FPN-ms-3x.pth`.

**Comment by cansik** [comment]
Great! thank you very much!
