### ISSUE TITLE
The gap between the results of our training centermask_R_101_FPN_ms_3x.yaml and the record of the paper

### ISSUE THREAD

**Issue by luyao-cv** [youngwanLEE/centermask2#85]
We used the configuration of centermask_R_101_FPN_ms_3x.yaml and ran it, and found that the performance of the mask ap was only 38.7 on test-dev. But in the table 5 of your paper, this mask ap achieved at 39.8. Can you share me with your centermask_R_101_FPN_ms_3x weights?

**Comment by youngwanLEE** [comment]
@luyao-cv Hi,

I share the [model weight](https://dl.dropbox.com/s/iq3i1ierv98momo/centermask2-R-101-FPN-ms-3x.pth), [metric](https://dl.dropbox.com/s/3x49zk629c2dao1/centermask2-R-101-FPN-ms-3x-metrics.json), [train_log](https://dl.dropbox.com/s/incuu1k20yy15nn/centermask2-R-50-FPN-ms-3x-log.txt) and [test-dev result](https://gist.github.com/youngwanLEE/8328784b13275bec8039365cc5ff7a94).

**Comment by luyao-cv** [comment]
> @luyao-cv Hi,
> 
> I share the [model weight](https://dl.dropbox.com/s/iq3i1ierv98momo/centermask2-R-101-FPN-ms-3x.pth), [train log](https://dl.dropbox.com/s/3x49zk629c2dao1/centermask2-R-101-FPN-ms-3x-metrics.json), and [test-dev result](https://gist.github.com/youngwanLEE/8328784b13275bec8039365cc5ff7a94).

thank you very much for your sharing, but the train log you provide is the metrics, we want to know why the gap is so big, could you please share your train log, we want to know whether the config we use is wrong.

**Comment by youngwanLEE** [comment]
@luyao-cv 
update above comment. check it.

**Comment by youngwanLEE** [comment]
Please re-open this issue if you face another problem.
