### ISSUE TITLE
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by Ultraopxt** [youngwanLEE/centermask2#88]
Hi , Thanks for your great job.
I train the net and got this error:RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)
My CUDA version is 11.1 and pytorch is 1.7.

**Comment by arkansawdave74** [comment]
Hello. I'm getting the same error, except I'm on Cuda-9.1. Here's my GPU info.

_Device-2: NVIDIA GF108GLM [Quadro 1000M] vendor: Lenovo driver: nvidia v: 390.144 bus-ID: 01:00.0
chip-ID: 10de:0dfa class-ID: 0300

Strang thing is,  hashcat was actually working before I installed cuda. Now it seems to be broken...._
