### ISSUE TITLE
FloatingPointError: Loss became infinite or NaN at iteration=137!

### ISSUE THREAD

**Issue by AlexFridman** [youngwanLEE/centermask2#9]
Hi! Got the error `FloatingPointError: Loss became infinite or NaN at iteration=137!`
Any help is applicable! Thanks!

```

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/alfrid/Documents/repos/centermask2/train_net.py", line 338, in main
    return trainer.train()
  File "/home/alfrid/Documents/repos/centermask2/train_net.py", line 201, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/home/alfrid/Documents/repos/centermask2/train_net.py", line 190, in train_loop
    self.run_step()
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 216, in run_step
    self._detect_anomaly(losses, loss_dict)
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 239, in _detect_anomaly
    self.iter, loss_dict
FloatingPointError: Loss became infinite or NaN at iteration=137!
loss_dict = {'loss_mask': tensor(0.7000, device='cuda:1', grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_maskiou': tensor(0., device='cuda:1', grad_fn=<MulBackward0>), 'loss_fcos_cls': tensor(nan, device='cuda:1', grad_fn=<DivBackward0>), 'loss_fcos_loc': tensor(nan, device='cuda:1', grad_fn=<DivBackward0>), 'loss_fcos_ctr': tensor(nan, device='cuda:1', grad_fn=<DivBackward0>)}

```

```
python train_net.py --config-file configs/centermask/centermask_V_99_eSE_FPN_ms_3x.yaml  --num-gpus 2```


```    
    cfg.DATASETS.TRAIN = tuple(DATASETS)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
    cfg.MODEL.FCOS.NUM_CLASSES = 1
    cfg.MODEL.RETINANET.NUM_CLASSES = 1
    cfg.OUTPUT_DIR = OUTPUT_DIR
    cfg.SOLVER.CHECKPOINT_PERIOD = 500
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.SOLVER.MAX_ITER = 1250000
    # cfg.VIS_PERIOD = 100
    cfg.TEST.DETECTIONS_PER_IMAGE = 500
```

**Comment by Rick-960123** [comment]
I have the same problem. Have you solved it？

**Comment by youngwanLEE** [comment]
@AlexFridman 
What kinds of the dataset you use?

Our results were from 8 GPUs and 16 batch size on COCO dataset.

If you use own dataset and different number of GPUs, you need to find proper hyperparameters such as base_lr, batch size, WARMUP_ITERS, and so on.

If you have 8 or fewer GPUs, try the following tricsk:

- reducing base_lr
- increasing [SOLVER.WARMUP_ITERS](https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py#L510)
- increasing batch size or change the backbone to the lightweight model

**Comment by AlexFridman** [comment]
Thank you, @youngwanLEE for the quick response! I suspect there's an issue in my annotations.

**Comment by freedom521jin** [comment]
There is somthing wrong with your label,the json files,maybe.I have made it.

**Comment by fshamsafar** [comment]
> * WARMUP_ITERS

I am having the same problem. Training stops in different number of iterations in different trials (once in 251, once in 1911, etc). 
I am running on 1 GPU with own dataset and with the light weight backbone of centermask2_lite_V_19_slim_dw_eSE_FPN. Also, I have tried decreasing the BASE_LR, increasing the WARMUP_ITERS and increasing the IMS_PER_BATCH (up to the point that GPU allows). 
Is it related to detectron2?

**Comment by lx709** [comment]
Same problem. Have you found out what's wrong with your own dataset? Thanks. @AlexFridman @f-sh-f-sh

**Comment by becks-ddf** [comment]
same problem even after 0 iterations

**Comment by XiaoMingDe** [comment]
+1, floatingpointerror  ......at iteration=1

**Comment by JPLeoRX** [comment]
> +1, floatingpointerror ......at iteration=1

+1, this issue still exists, I encountered it when trying to train a model without using pre-trained weights. Increasing WARMUP_ITERS or IMS_PER_BATCH did not help, neither did tweaking the BASE_LR

**Comment by VladKatsman** [comment]
Probably, we should consider writing custom loss functions, with simple clip (0, 1) properties for critical computations
