### ISSUE TITLE
KeyError: "No object named 'build_fcos_vovnet_fpn_backbone' found in 'BACKBONE' registry!"

### ISSUE THREAD

**Issue by Ultraopxt** [youngwanLEE/centermask2#94]
Hi, When  I run the demo.py on docker and I met the following problem:

KeyError: "No object named 'build_fcos_vovnet_fpn_backbone' found in 'BACKBONE' registry!"

Thanks.

**Comment by ThelilinNB** [comment]
Hello, have you solved this problem

**Comment by FruitPigFoot** [comment]
need help on this too

**Comment by ThelilinNB** [comment]
> need help on this too

hi, do you have the same problem? Have you found a solution? Can we discuss it? Thank you

**Comment by FruitPigFoot** [comment]
actually i'm trying to do an inference on vovnet. However, not much discussion is going on there so i'm trying to find some help elsewhere. What are you trying to do?

**Comment by FruitPigFoot** [comment]
i managed to solve it

**Comment by ThelilinNB** [comment]
> i managed to solve it

can you tell me how you solved it? This problem has been bothering me for several days, but I still haven't found a solution. I am very eager to get your help, thank you bro

**Comment by FruitPigFoot** [comment]
in my instance i had to add code line : add_vovnet_config(cfg)  and also had to import the add_vovnet_config. It has gotta be the same on centermask too. Or else can you upload the code where it's bothering you?

**Comment by ThelilinNB** [comment]
> in my instance i had to add code line : add_vovnet_config(cfg) and also had to import the add_vovnet_config. It has gotta be the same on centermask too. Or else can you upload the code where it's bothering you?

Sorry, I just saw the information today. As for the add_vovnet_congig(cfg) you said, I can't understand where to add this part. Could you please upload the modified part of the code so that I can see it more intuitively

**Comment by FruitPigFoot** [comment]
this is doing inference on one image using the detectron method. the code should be running in the appropriate directory

import detectron2
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from vovnet_detectron2.vovnet.config import add_vovnet_config
# Load a pre-trained VovNet-based model
cfg = get_cfg()
print(1)
add_vovnet_config(cfg) ----------->this is the part i was talking about
print(2)
cfg.merge_from_file("~~~~~~~~")  # Specify your model's configuration file
cfg.OUTPUT_DIR = "~~~~~~~"  # Specify the path to your pre-trained checkpoint
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.6

**Comment by ThelilinNB** [comment]
> this is doing inference on one image using the detectron method. the code should be running in the appropriate directory
> 
> import detectron2 from detectron2.engine import DefaultPredictor from detectron2.config import get_cfg from vovnet_detectron2.vovnet.config import add_vovnet_config
> 
> # Load a pre-trained VovNet-based model
> cfg = get_cfg() print(1) add_vovnet_config(cfg) ----------->this is the part i was talking about print(2) cfg.merge_from_file("~~~~~~~~") # Specify your model's configuration file cfg.OUTPUT_DIR = "~~~~~~~" # Specify the path to your pre-trained checkpoint cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth") cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.6

I have also solved this problem. Thank you very much for your help
